In [1]:
import sys
import numpy as np

In [2]:
np.array([1, 2, 3])

array([1, 2, 3])

In [3]:
a = np.array([1, 2, 3, 4])

In [4]:
b = np.array([0, .5, 1, 1.5, 2])

In [5]:
a.dtype

dtype('int64')

In [6]:
b.dtype

dtype('float64')

In [7]:
c = np.array([1, 2, 3, 4], dtype=np.float)

In [8]:
c.dtype

dtype('float64')

In [9]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]], dtype=np.float)

In [10]:
A.dtype

dtype('float64')

In [11]:
A.shape

(3, 3)

In [12]:
B = np.array([[-1, -2, 3], [4, -5, 6], [7, -8, 9]], dtype=np.float)

In [13]:
A

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [14]:
B

array([[-1., -2.,  3.],
       [ 4., -5.,  6.],
       [ 7., -8.,  9.]])

In [15]:
A * B

array([[ -1.,  -4.,   9.],
       [ 16., -25.,  36.],
       [ 49., -64.,  81.]])

In [16]:
A / B

array([[-1., -1.,  1.],
       [ 1., -1.,  1.],
       [ 1., -1.,  1.]])

In [17]:
A.ndim

2

In [18]:
A.size

9

In [19]:
a.size

4

In [20]:
a.ndim

1

In [21]:
a.shape

(4,)

In [22]:
A

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [23]:
A[1] = np.array([10, 10, 10])

In [24]:
A[2] = 99

In [25]:
A

array([[ 1.,  2.,  3.],
       [10., 10., 10.],
       [99., 99., 99.]])

I's magic with NumPy, and I really love it!!!

# Summary statistics

In [26]:
a = np.array([1, 2, 3, 4])

In [27]:
a.sum()

10

In [28]:
a.mean()

2.5

In [29]:
a.std()

1.118033988749895

In [30]:
a.var()

1.25

In [31]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6.],
    [7, 8, 9]])

In [32]:
A.sum()

45.0

In [33]:
A.mean()

5.0

In [34]:
A.std()

2.581988897471611

In [35]:
A.std(axis=0)

array([2.44948974, 2.44948974, 2.44948974])

In [36]:
A.sum(axis=0)

array([12., 15., 18.])

In [37]:
A.var()

6.666666666666667

In [38]:
A.var(axis=0)

array([6., 6., 6.])

# Broadcasting and Vectorized operations

In [39]:
a = np.arange(4)

In [40]:
a

array([0, 1, 2, 3])

In [41]:
a + 10

array([10, 11, 12, 13])

In [42]:
a * 10

array([ 0, 10, 20, 30])

In [43]:
a

array([0, 1, 2, 3])

In [44]:
a += 100

In [45]:
a

array([100, 101, 102, 103])

In [46]:
l = [0, 1, 2, 3]

In [47]:
[i * 10 for i in l]

[0, 10, 20, 30]

In [48]:
a = np.arange(4)

In [49]:
a

array([0, 1, 2, 3])

In [50]:
a

array([0, 1, 2, 3])

In [51]:
b = np.array([10, 10, 10, 10])

In [52]:
a + b

array([10, 11, 12, 13])

In [53]:
a * b

array([ 0, 10, 20, 30])

# Boolean array in NumPy

In [54]:
a = np.arange(4)

In [55]:
a

array([0, 1, 2, 3])

In [56]:
a[0], a[-1]

(0, 3)

In [57]:
a[[0, -1]]

array([0, 3])

In [58]:
a[[True, False, False, True]]

array([0, 3])

In [59]:
a >= 2

array([False, False,  True,  True])

In [60]:
a[a >= 2]

array([2, 3])

In [61]:
a.mean()

1.5

In [62]:
a[a > a.mean()]

array([2, 3])

In [64]:
a[~(a > a.mean())]

array([0, 1])

In [65]:
a[(a == 0) | (a == 1)]

array([0, 1])

In [66]:
a[(a <= 2) & (a % 2 == 0)]

array([0, 2])

In [67]:
A = np.random.randint(100, size=(3, 3))

In [68]:
A

array([[26, 77, 14],
       [54,  9, 67],
       [64, 44, 59]])

In [74]:
A[np.array([
    [True, False, True],
    [False, True, False],
    [True, False, True]
])]

array([26, 14,  9, 64, 59])

In [75]:
A

array([[26, 77, 14],
       [54,  9, 67],
       [64, 44, 59]])

In [76]:
A > 30

array([[False,  True, False],
       [ True, False,  True],
       [ True,  True,  True]])

In [77]:
A[A > 30]

array([77, 54, 67, 64, 44, 59])

In [78]:
a = np.array([0, 1, 2, 3])

In [79]:
b = np.array([0, 2, 3, 4])

In [80]:
a == b

array([ True, False, False, False])

# NumPy Linear Algebra

In [81]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [83]:
B = np.array([
    [6, 5],
    [4, 3],
    [2, 1]
])

Dot product

In [86]:
A.dot(B)

array([[20, 14],
       [56, 41],
       [92, 68]])

Cross produt

In [85]:
A @ B

array([[20, 14],
       [56, 41],
       [92, 68]])

In [87]:
B.T

array([[6, 4, 2],
       [5, 3, 1]])

In [88]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [89]:
B.T @ A

array([[36, 48, 60],
       [24, 33, 42]])

In [95]:
C = np.array([
    [1, 1, -1],
    [1, 1, -1],
    [1, 1, -1]
])

In [96]:
A.dot(C)

array([[  6,   6,  -6],
       [ 15,  15, -15],
       [ 24,  24, -24]])

In [97]:
C.dot(A)

array([[-2, -1,  0],
       [-2, -1,  0],
       [-2, -1,  0]])

.

.

# Size of objects in Memory

In [101]:
# an integer in Python is > 24 bytes
sys.getsizeof(1)

28

In [103]:
# longs are even larger
sys.getsizeof(10**100)

72

In [105]:
# Numpy size is much smaller
np.dtype(int).itemsize

8

In [107]:
# Numpy size is much smaller
np.dtype(np.int8).itemsize

1

In [108]:
np.dtype(float).itemsize

8

### List are even larger

In [109]:
# a one element list
sys.getsizeof([1])

72

In [110]:
# an array of one element in NumPy
np.array([1]).nbytes

8

### And performance is also important

In [119]:
l = list(range(100000))
a = np.arange(100000)

In [120]:
%time np.sum(a ** 2)

CPU times: user 1.05 ms, sys: 0 ns, total: 1.05 ms
Wall time: 3.09 ms


333328333350000

In [121]:
%time sum([x ** 2 for x in l])

CPU times: user 25.6 ms, sys: 3.37 ms, total: 29 ms
Wall time: 28.6 ms


333328333350000

.

.

# Usefull NumPy functions

### random

In [122]:
np.random.random(size=2)

array([0.17470358, 0.48154647])

In [123]:
np.random.normal(size=2)

array([ 0.29444969, -0.51512665])

In [124]:
np.random.rand(2, 4)

array([[0.00451029, 0.07616871, 0.05847018, 0.77911743],
       [0.9011573 , 0.30295568, 0.66068094, 0.27060634]])

### arange

In [125]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [126]:
np.arange(5, 10)

array([5, 6, 7, 8, 9])

In [127]:
np.arange(0, 1, 0.1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

### reshape

In [128]:
np.arange(10).reshape(2, 5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [129]:
np.arange(10).reshape(5, 2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

### linspace

In [130]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [131]:
np.linspace(0, 1, 20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [132]:
np.linspace(0, 1, 20, False)

array([0.  , 0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 ,
       0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95])

### zeros, ones, empty

In [133]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [134]:
np.zeros((3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [136]:
np.zeros((3, 3), dtype=np.int)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [137]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [138]:
np.ones((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [139]:
np.empty(5)

array([1., 1., 1., 1., 1.])

In [140]:
np.empty((2, 2))

array([[0.25, 0.5 ],
       [0.75, 1.  ]])

### identyty and eye

In [141]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [142]:
np.eye(3, 3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [144]:
np.eye(8, 4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [145]:
np.eye(8, 4, k=1)

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [146]:
np.eye(8, 4, k=-3)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

In [147]:
"Hello World"[6]

'W'